### ISSUE TITLE
Avoid conditional imports

### ISSUE THREAD

**Issue by jaraco** [jaraco/backports.typing#1]
Originally reported by: **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**

---

@agronholm makes this request:

Would it be possible to release a new version of this package so that it enables imports from the "typing" module directly so I wouldn't have to do awkward conditional imports to work with both Python 3.4 and 3.5? I'm not really seeing why it has to be prefixed with "backports" anyway.

Thanks.

---
- Bitbucket: https://bitbucket.org/jaraco/backports.typing/issue/1

**Comment by jaraco** [comment]
_Original comment by_ **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**:

---

I do apologize that the readme is still essentially empty. It should at least provide some usage.

Backports follows the guidance given by the [parent project](https://pypi.python.org/pypi/backports).

Following that guidance, the recommended usage on any Python is to use the backport implementation (even on Python 3.5 and later).

Does it make sense to instead offer `typing` outside of the `backports` namespace, akin to `importlib` or `argparse`? @brandon, do you have an opinion?

Now that I search, I see [typing 0.0](https://pypi.python.org/pypi/typing) already exists, though it is only squatting on the name and doesn't have any implementation.

My inclination is for this package to support typing in a separate namespace and following the backports convention. If at some time, the `typing` package obviates the need for this one, I'll mark this one as deprecated.

**Comment by jaraco** [comment]
_Original comment by_ **Alex Grönholm (Bitbucket: [agronholm](http://bitbucket.org/agronholm), GitHub: [agronholm](http://github.com/agronholm))**:

---

Yes, I would like to use the "typing" package as it is, and I already found typing-0.0 to be completely useless, which is why I'm asking. But perhaps I should convince the authors to replace it with something useful, like this one.

**Comment by jaraco** [comment]
_Original comment by_ **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**:

---

Alex, why not unconditionally require backports.typing and `from backports import typing` until Python 3.4 and earlier are unsupported? Then you get the benefit of having a known, consistent implementation across all Pythons until such a time that you switch to the stdlib version.

**Comment by jaraco** [comment]
_Original comment by_ **Alex Grönholm (Bitbucket: [agronholm](http://bitbucket.org/agronholm), GitHub: [agronholm](http://github.com/agronholm))**:

---

It seems dumb having to install backports.typing on Python 3.5. And are you suggesting that the backport will have a different API?

**Comment by jaraco** [comment]
_Original comment by_ **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**:

---

No, it shouldn't have a different API, but if the stdlib version changes or there are subtle differences necessary to maintain the backport, those will remain stable across all deployments of your lib/app. Say Python 3.6 adds another function or 3.5.1 fixes a flaw - the backport will be inconsistent with that implementation until the backport is updated. Furthermore, if 3.6 adds a function and it's backported to backports, it will appear in 3.6 and 3.4, but not 3.5. That's the reasoning behind the backports guidance.

**Comment by jaraco** [comment]
_Original comment by_ **Alex Grönholm (Bitbucket: [agronholm](http://bitbucket.org/agronholm), GitHub: [agronholm](http://github.com/agronholm))**:

---

I wouldn't use anything that's not supported across all versions. And there's another consideration: PyCharm's PEP 484 support may not recognize backports.typing as the official typing module, so static type analysis may not work with it.

**Comment by jaraco** [comment]
_Original comment by_ **Antti Haapala (Bitbucket: [antti_haapala](http://bitbucket.org/antti_haapala), GitHub: Unknown)**:

---

+1 now that PyCharm's gotten much better with type inferencing it is notable that it fails to work at all with `backports.typing`; instead I get warnings like `backports.typing.Any was expected, str was given`.

**Comment by jaraco** [comment]
_Original comment by_ **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**:

---

What is the proposal here? Should backports.typing just present a typing module? What happens if that's installed on python 3.5? Or should backports.typing present a function that can be called to install backports.typing as sys.modules['typing']? Under what circumstances will PyCharm honor this backport? I'm happy to accept any suggestions that are useful to the users.

**Comment by jaraco** [comment]
_Original comment by_ **Jason R. Coombs (Bitbucket: [jaraco](http://bitbucket.org/jaraco), GitHub: [jaraco](http://github.com/jaraco))**:

---

Looking at the typing package in PyPI, it seems to have obviates this package. I'm just going to stub it out and have it reference the typing package.

**Comment by agronholm** [comment]
The typing package is constantly evolving. How will we get updates for older Pythons (3.5.1 and 3.5.0) if not through this library?

**EDIT**: This was pointed out earlier but I find the answer unacceptable.

**Comment by jaraco** [comment]
@agronholm Good question. From your comment:

> I wouldn't use anything that's not supported across all versions. 

I got the sense that you were content to rely on whatever 'typing' module was available, whether that be the stdlib-provided version (which might be stale/old) or the backport (on Python 3.4 and earlier). That's what this new implementation is seeking to do.

If what you're seeking to have instead is to have a backport that brings 3.5.2 changes back to 3.5.1 and 3.5.0, I don't think the `typing` namespace can be re-used, and the code needs to be maintained separately in the `backports.typing` namespace.

Perhaps there's a way this library could support both models, where it conditionally requires the "official" typing backport on relevant platforms, making `import typing` work on all environments, but also supplies `backports.typing` which is maintained for a reliable copy of the code as found in the official backport for use on any platform, including those that have `typing` in the stdlib.

**Comment by agronholm** [comment]
Yes, what I intended to say is that backports.typing is still needed in order to get the improvements from 3.5.2 and beyond. The tooling should also be changed to support this (I have a ticket open for PyCharm regarding that). I really wish the stdlib switched to a different distribution model so this wouldn't be necessary but this workaround is at least something we can realistically accomplish in any reasonable timeframe.

**Comment by jaraco** [comment]
I'm pushing out backports.typing 1.1 with a fix for this issue. Overall, I'm pretty pleased with the implementation. Please review the changes or try out the new release and share your feedback, create a new issue, or send a PR.

**Comment by agronholm** [comment]
Looks good to me!

**Comment by agronholm** [comment]
I have to take that back. Tried installing this on py3.3 and "import typing" does not work.

**Comment by jaraco** [comment]
I should add a note that the conditional dependencies does require late-ish versions of pip and setuptools.
